table dim_customer
	lineageTag: 358563d0-e8f1-4c31-90c9-0797fd8cde07

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: a5a4b193-6dae-4476-90d5-fab04d2477a0
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 4aa10697-00b7-4cd3-ad1c-9bec37a2564f
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 8e48749d-28cb-4a4a-a225-743a61e814c7
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: ab116ae4-9012-435a-ac7a-ed861e9ea46d
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = Automatic

	column payment_terms
		dataType: string
		lineageTag: c3bf6a51-b67a-450f-9bec-43c221edf86c
		summarizeBy: none
		sourceColumn: payment_terms

		annotation SummarizationSetBy = Automatic

	column contact_name
		dataType: string
		lineageTag: 35013868-3b83-405c-972e-9a41610da983
		summarizeBy: none
		sourceColumn: contact_name

		annotation SummarizationSetBy = Automatic

	column contact_email
		dataType: string
		lineageTag: 3c155c5e-0fdf-4efa-b654-8fba0395a76b
		summarizeBy: none
		sourceColumn: contact_email

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: int64
		formatString: 0
		lineageTag: d35e5345-93a1-4fda-9a65-f0d34e68be87
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: bfb148f0-07f4-40e1-aaa2-b6e55b5db345
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column street
		dataType: string
		lineageTag: 86a0d445-367a-49dc-8d86-dd04b4cbe8a9
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 8c94d659-3b18-4972-af97-8133f1f63bc3
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 4f7c081b-304a-48c0-9f10-99fb4f8bc913
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Source = CUST_MASTER,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([CustomerID] <> 9999)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"CustomerID"}, customer_contacts, {"CustomerID"}, "customer_contacts", JoinKind.LeftOuter),
				    #"Expanded customer_contacts" = Table.ExpandTableColumn(#"Merged Queries", "customer_contacts", {"ContactName", "Email", "IsPrimary"}, {"customer_contacts.ContactName", "customer_contacts.Email", "customer_contacts.IsPrimary"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded customer_contacts", {"CustomerID"}, user_details, {"UserID"}, "user_details", JoinKind.LeftOuter),
				    #"Expanded user_details" = Table.ExpandTableColumn(#"Merged Queries1", "user_details", {"CreditLimit", "Phone"}, {"user_details.CreditLimit", "user_details.Phone"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded user_details", {"AddressID"}, Address, {"AddressID"}, "Address", JoinKind.LeftOuter),
				    #"Expanded Address" = Table.ExpandTableColumn(#"Merged Queries2", "Address", {"Street", "CityName"}, {"Address.Street", "Address.CityName"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Address", {"Address.CityName"}, cities, {"CityName"}, "cities", JoinKind.LeftOuter),
				    #"Expanded cities" = Table.ExpandTableColumn(#"Merged Queries3", "cities", {"RegionName"}, {"cities.RegionName"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded cities",{"AddressID", "hash_key", "source_id", "customer_contacts.IsPrimary"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"CustomerID", "customer_id"}, {"CustomerName", "customer_name"}, {"Segment", "segment"}, {"AccountManager", "account_manager"}, {"PaymentTerms", "payment_terms"}, {"customer_contacts.ContactName", "contact_name"}, {"customer_contacts.Email", "contact_email"}, {"user_details.CreditLimit", "credit_limit"}, {"user_details.Phone", "phone"}, {"Address.Street", "street"}, {"Address.CityName", "city"}, {"cities.RegionName", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

