table fact_sales_targets
	lineageTag: b28ade05-aa79-4cd2-881c-3676bd612b32

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 136d42f9-eaf8-47af-ac34-33374f75a982
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column target_revenue
		dataType: int64
		formatString: 0
		lineageTag: 52a03500-d1d6-4f11-9166-10b73a3099e7
		summarizeBy: sum
		sourceColumn: target_revenue

		annotation SummarizationSetBy = Automatic

	partition fact_sales_targets = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = sales_targets,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Period", "date"}, {"TargetRevenue", "target_revenue"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

