table security
	lineageTag: 3e927e5e-dd70-4b9f-962f-c0298f08fc45

	column user_email
		dataType: string
		lineageTag: 91f123e0-7743-4eed-a270-7b646a8d6aed
		summarizeBy: none
		sourceColumn: user_email

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 18b04a51-e324-4d2c-a1b9-cf253f7d99fe
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition security = m
		mode: import
		queryGroup: 04_Support
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Mac\Home\Documents\PowerBI\Datasets\data-modeling\before_model.xlsx"), null, true),
				    security_Sheet = Source{[Item="security",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(security_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"UserEmail", type text}, {"Region", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"UserEmail", "user_email"}, {"Region", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

